pipeline {
    agent { label 'master' }
    stages {
        stage('build') {
            steps {
                echo 'Build Project'
              sh 'mvn -B -DskipTests clean package'
	    }
	}
    }	
}
